title: ohutus.github.io
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima

minima:
  skin: solarized

url: https://ohutus.github.io

author:
  name: ohutus(valeNimi4)
  links:
    - title: GitHub
      icon: github
      url: https://github.com/sinu-kasutajanimi
